name: ECMPS Automated Tests

on:
  workflow_dispatch:

jobs:
  Automated-Tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Install Chrome
        run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install ./google-chrome-stable_current_amd64.deb
          
      - name: Download ChromeDriver
        run: |
          cd ~
          mkdir ~/drivers
          sudo npm install chromedriver
          ln -sf ~/node_modules/chromedriver/lib/chromedriver/chromedriver ~/drivers/chromedriver
      
      - name: Run Tests
        run: mvn test -Dname=Test_ECMPSUI_SMK_MonPlanPage
